/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 17
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  aux_sym_comment_token1 = 5,
  sym__comment_content = 6,
  anon_sym_LT = 7,
  anon_sym_SLASH_GT = 8,
  anon_sym_LT_SLASH = 9,
  anon_sym_EQ = 10,
  sym_attribute_name = 11,
  sym_attribute_value = 12,
  sym_entity = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_quoted_attribute_value_token1 = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_quoted_attribute_value_token2 = 17,
  sym_text = 18,
  sym__start_tag_name = 19,
  sym__script_start_tag_name = 20,
  sym__style_start_tag_name = 21,
  sym__end_tag_name = 22,
  sym_erroneous_end_tag_name = 23,
  sym__implicit_end_tag = 24,
  sym_raw_text = 25,
  sym_include_comment = 26,
  sym_ignoreif_comment = 27,
  sym_normal_comment = 28,
  sym_include_identifier = 29,
  sym_ignoreif_identifier = 30,
  sym_unknown_identifier = 31,
  sym__comment_start = 32,
  sym_include_directive = 33,
  sym__comment_end = 34,
  sym_document = 35,
  sym_doctype = 36,
  sym__node = 37,
  sym_comment = 38,
  sym_element = 39,
  sym_script_element = 40,
  sym_style_element = 41,
  sym_start_tag = 42,
  sym_script_start_tag = 43,
  sym_style_start_tag = 44,
  sym_self_closing_tag = 45,
  sym_end_tag = 46,
  sym_erroneous_end_tag = 47,
  sym_attribute = 48,
  sym_quoted_attribute_value = 49,
  aux_sym_document_repeat1 = 50,
  aux_sym_start_tag_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__comment_content] = "_comment_content",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_include_comment] = "include_comment",
  [sym_ignoreif_comment] = "ignoreif_comment",
  [sym_normal_comment] = "normal_comment",
  [sym_include_identifier] = "include_identifier",
  [sym_ignoreif_identifier] = "ignoreif_identifier",
  [sym_unknown_identifier] = "unknown_identifier",
  [sym__comment_start] = "_comment_start",
  [sym_include_directive] = "include_directive",
  [sym__comment_end] = "_comment_end",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_comment] = "comment",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__comment_content] = sym__comment_content,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_include_comment] = sym_include_comment,
  [sym_ignoreif_comment] = sym_ignoreif_comment,
  [sym_normal_comment] = sym_normal_comment,
  [sym_include_identifier] = sym_include_identifier,
  [sym_ignoreif_identifier] = sym_ignoreif_identifier,
  [sym_unknown_identifier] = sym_unknown_identifier,
  [sym__comment_start] = sym__comment_start,
  [sym_include_directive] = sym_include_directive,
  [sym__comment_end] = sym__comment_end,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_comment] = sym_comment,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__comment_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_include_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_ignoreif_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_include_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_ignoreif_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_start] = {
    .visible = false,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_end] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 11,
  [22] = 22,
  [23] = 23,
  [24] = 10,
  [25] = 13,
  [26] = 14,
  [27] = 15,
  [28] = 16,
  [29] = 17,
  [30] = 18,
  [31] = 9,
  [32] = 20,
  [33] = 33,
  [34] = 33,
  [35] = 22,
  [36] = 23,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 39,
  [41] = 37,
  [42] = 42,
  [43] = 38,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 50,
  [55] = 55,
  [56] = 42,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 55,
  [64] = 57,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 70,
  [72] = 61,
  [73] = 73,
  [74] = 73,
  [75] = 62,
  [76] = 60,
  [77] = 51,
  [78] = 66,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 80,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 83,
  [91] = 91,
  [92] = 84,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 91,
  [97] = 94,
  [98] = 98,
  [99] = 91,
  [100] = 100,
  [101] = 88,
  [102] = 79,
  [103] = 100,
  [104] = 85,
  [105] = 85,
  [106] = 81,
  [107] = 93,
  [108] = 93,
  [109] = 82,
  [110] = 82,
  [111] = 87,
  [112] = 87,
  [113] = 89,
  [114] = 89,
  [115] = 98,
  [116] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 79,
        '&', 3,
        '\'', 76,
        '/', 7,
        '<', 30,
        '=', 33,
        '>', 24,
        'D', 10,
        'd', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\'') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(18);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '>') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(34);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 14:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 15:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(82);
      END_STATE();
    case 16:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(29);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '<') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(82);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead == '-') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 19, .external_lex_state = 2},
  [2] = {.lex_state = 19, .external_lex_state = 3},
  [3] = {.lex_state = 19, .external_lex_state = 3},
  [4] = {.lex_state = 19, .external_lex_state = 3},
  [5] = {.lex_state = 19, .external_lex_state = 3},
  [6] = {.lex_state = 19, .external_lex_state = 2},
  [7] = {.lex_state = 19, .external_lex_state = 2},
  [8] = {.lex_state = 19, .external_lex_state = 3},
  [9] = {.lex_state = 19, .external_lex_state = 2},
  [10] = {.lex_state = 19, .external_lex_state = 2},
  [11] = {.lex_state = 19, .external_lex_state = 2},
  [12] = {.lex_state = 19, .external_lex_state = 3},
  [13] = {.lex_state = 19, .external_lex_state = 2},
  [14] = {.lex_state = 19, .external_lex_state = 2},
  [15] = {.lex_state = 19, .external_lex_state = 2},
  [16] = {.lex_state = 19, .external_lex_state = 2},
  [17] = {.lex_state = 19, .external_lex_state = 2},
  [18] = {.lex_state = 19, .external_lex_state = 2},
  [19] = {.lex_state = 19, .external_lex_state = 3},
  [20] = {.lex_state = 19, .external_lex_state = 2},
  [21] = {.lex_state = 19, .external_lex_state = 3},
  [22] = {.lex_state = 19, .external_lex_state = 3},
  [23] = {.lex_state = 19, .external_lex_state = 3},
  [24] = {.lex_state = 19, .external_lex_state = 3},
  [25] = {.lex_state = 19, .external_lex_state = 3},
  [26] = {.lex_state = 19, .external_lex_state = 3},
  [27] = {.lex_state = 19, .external_lex_state = 3},
  [28] = {.lex_state = 19, .external_lex_state = 3},
  [29] = {.lex_state = 19, .external_lex_state = 3},
  [30] = {.lex_state = 19, .external_lex_state = 3},
  [31] = {.lex_state = 19, .external_lex_state = 3},
  [32] = {.lex_state = 19, .external_lex_state = 3},
  [33] = {.lex_state = 19, .external_lex_state = 2},
  [34] = {.lex_state = 19, .external_lex_state = 3},
  [35] = {.lex_state = 19, .external_lex_state = 2},
  [36] = {.lex_state = 19, .external_lex_state = 2},
  [37] = {.lex_state = 6, .external_lex_state = 4},
  [38] = {.lex_state = 6, .external_lex_state = 4},
  [39] = {.lex_state = 6, .external_lex_state = 4},
  [40] = {.lex_state = 6, .external_lex_state = 4},
  [41] = {.lex_state = 6, .external_lex_state = 4},
  [42] = {.lex_state = 6, .external_lex_state = 4},
  [43] = {.lex_state = 6, .external_lex_state = 5},
  [44] = {.lex_state = 6, .external_lex_state = 5},
  [45] = {.lex_state = 6, .external_lex_state = 5},
  [46] = {.lex_state = 6, .external_lex_state = 5},
  [47] = {.lex_state = 6, .external_lex_state = 5},
  [48] = {.lex_state = 1, .external_lex_state = 5},
  [49] = {.lex_state = 1, .external_lex_state = 5},
  [50] = {.lex_state = 0, .external_lex_state = 6},
  [51] = {.lex_state = 6, .external_lex_state = 4},
  [52] = {.lex_state = 0, .external_lex_state = 6},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0, .external_lex_state = 6},
  [55] = {.lex_state = 6, .external_lex_state = 4},
  [56] = {.lex_state = 6, .external_lex_state = 5},
  [57] = {.lex_state = 6, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 7},
  [59] = {.lex_state = 0, .external_lex_state = 7},
  [60] = {.lex_state = 6, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 2, .external_lex_state = 5},
  [63] = {.lex_state = 6, .external_lex_state = 5},
  [64] = {.lex_state = 6, .external_lex_state = 5},
  [65] = {.lex_state = 0, .external_lex_state = 6},
  [66] = {.lex_state = 0, .external_lex_state = 8},
  [67] = {.lex_state = 0, .external_lex_state = 6},
  [68] = {.lex_state = 0, .external_lex_state = 6},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 0, .external_lex_state = 5},
  [72] = {.lex_state = 0, .external_lex_state = 5},
  [73] = {.lex_state = 4, .external_lex_state = 5},
  [74] = {.lex_state = 4, .external_lex_state = 5},
  [75] = {.lex_state = 2, .external_lex_state = 5},
  [76] = {.lex_state = 6, .external_lex_state = 5},
  [77] = {.lex_state = 6, .external_lex_state = 5},
  [78] = {.lex_state = 0, .external_lex_state = 8},
  [79] = {.lex_state = 0, .external_lex_state = 9},
  [80] = {.lex_state = 0, .external_lex_state = 5},
  [81] = {.lex_state = 0, .external_lex_state = 5},
  [82] = {.lex_state = 26, .external_lex_state = 5},
  [83] = {.lex_state = 0, .external_lex_state = 5},
  [84] = {.lex_state = 0, .external_lex_state = 5},
  [85] = {.lex_state = 26, .external_lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 5},
  [87] = {.lex_state = 0, .external_lex_state = 10},
  [88] = {.lex_state = 16, .external_lex_state = 5},
  [89] = {.lex_state = 26, .external_lex_state = 5},
  [90] = {.lex_state = 0, .external_lex_state = 5},
  [91] = {.lex_state = 0, .external_lex_state = 11},
  [92] = {.lex_state = 0, .external_lex_state = 5},
  [93] = {.lex_state = 28, .external_lex_state = 5},
  [94] = {.lex_state = 0, .external_lex_state = 5},
  [95] = {.lex_state = 0, .external_lex_state = 5},
  [96] = {.lex_state = 0, .external_lex_state = 11},
  [97] = {.lex_state = 0, .external_lex_state = 5},
  [98] = {.lex_state = 0, .external_lex_state = 5},
  [99] = {.lex_state = 0, .external_lex_state = 11},
  [100] = {.lex_state = 0, .external_lex_state = 12},
  [101] = {.lex_state = 16, .external_lex_state = 5},
  [102] = {.lex_state = 0, .external_lex_state = 9},
  [103] = {.lex_state = 0, .external_lex_state = 12},
  [104] = {.lex_state = 26, .external_lex_state = 5},
  [105] = {.lex_state = 26, .external_lex_state = 5},
  [106] = {.lex_state = 0, .external_lex_state = 5},
  [107] = {.lex_state = 28, .external_lex_state = 5},
  [108] = {.lex_state = 28, .external_lex_state = 5},
  [109] = {.lex_state = 26, .external_lex_state = 5},
  [110] = {.lex_state = 26, .external_lex_state = 5},
  [111] = {.lex_state = 0, .external_lex_state = 10},
  [112] = {.lex_state = 0, .external_lex_state = 10},
  [113] = {.lex_state = 26, .external_lex_state = 5},
  [114] = {.lex_state = 26, .external_lex_state = 5},
  [115] = {.lex_state = 0, .external_lex_state = 5},
  [116] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_include_comment] = ACTIONS(1),
    [sym_ignoreif_comment] = ACTIONS(1),
    [sym_normal_comment] = ACTIONS(1),
    [sym_include_identifier] = ACTIONS(1),
    [sym_ignoreif_identifier] = ACTIONS(1),
    [sym_unknown_identifier] = ACTIONS(1),
    [sym__comment_start] = ACTIONS(3),
    [sym_include_directive] = ACTIONS(1),
    [sym__comment_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(95),
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_comment] = STATE(1),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(54),
    [sym_style_start_tag] = STATE(52),
    [sym_self_closing_tag] = STATE(11),
    [sym_erroneous_end_tag] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
    [sym_ignoreif_identifier] = ACTIONS(13),
    [sym_unknown_identifier] = ACTIONS(13),
    [sym__comment_start] = ACTIONS(15),
    [sym_include_directive] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(25), 1,
      sym__implicit_end_tag,
    ACTIONS(27), 1,
      sym__comment_start,
    STATE(2), 1,
      sym_comment,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(35), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(53), 1,
      sym_style_start_tag,
    ACTIONS(23), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(4), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [50] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      sym__comment_start,
    ACTIONS(29), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_comment,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(27), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(53), 1,
      sym_style_start_tag,
    ACTIONS(31), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [100] = 13,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym__comment_start,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_end_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(53), 1,
      sym_style_start_tag,
    ACTIONS(31), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [150] = 12,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      sym__comment_start,
    ACTIONS(29), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(22), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(53), 1,
      sym_style_start_tag,
    STATE(5), 2,
      sym_comment,
      sym_start_tag,
    ACTIONS(37), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(3), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [198] = 11,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_LT_BANG,
    ACTIONS(46), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LT_SLASH,
    ACTIONS(55), 1,
      sym__comment_start,
    STATE(2), 1,
      sym_start_tag,
    STATE(11), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_style_start_tag,
    STATE(54), 1,
      sym_script_start_tag,
    ACTIONS(52), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [243] = 12,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym__comment_start,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(7), 1,
      sym_comment,
    STATE(11), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym_style_start_tag,
    STATE(54), 1,
      sym_script_start_tag,
    ACTIONS(60), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [290] = 11,
    ACTIONS(41), 1,
      sym__implicit_end_tag,
    ACTIONS(62), 1,
      anon_sym_LT_BANG,
    ACTIONS(65), 1,
      anon_sym_LT,
    ACTIONS(68), 1,
      anon_sym_LT_SLASH,
    ACTIONS(74), 1,
      sym__comment_start,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(50), 1,
      sym_script_start_tag,
    STATE(53), 1,
      sym_style_start_tag,
    ACTIONS(71), 5,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym_include_directive,
      sym_entity,
      sym_text,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [335] = 3,
    ACTIONS(79), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_comment,
    ACTIONS(77), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [353] = 3,
    ACTIONS(83), 1,
      anon_sym_LT,
    STATE(10), 1,
      sym_comment,
    ACTIONS(81), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [371] = 3,
    ACTIONS(87), 1,
      anon_sym_LT,
    STATE(11), 1,
      sym_comment,
    ACTIONS(85), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [389] = 3,
    ACTIONS(91), 1,
      anon_sym_LT,
    STATE(12), 1,
      sym_comment,
    ACTIONS(89), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [407] = 3,
    ACTIONS(95), 1,
      anon_sym_LT,
    STATE(13), 1,
      sym_comment,
    ACTIONS(93), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [425] = 3,
    ACTIONS(99), 1,
      anon_sym_LT,
    STATE(14), 1,
      sym_comment,
    ACTIONS(97), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [443] = 3,
    ACTIONS(103), 1,
      anon_sym_LT,
    STATE(15), 1,
      sym_comment,
    ACTIONS(101), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [461] = 3,
    ACTIONS(107), 1,
      anon_sym_LT,
    STATE(16), 1,
      sym_comment,
    ACTIONS(105), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [479] = 3,
    ACTIONS(111), 1,
      anon_sym_LT,
    STATE(17), 1,
      sym_comment,
    ACTIONS(109), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [497] = 3,
    ACTIONS(115), 1,
      anon_sym_LT,
    STATE(18), 1,
      sym_comment,
    ACTIONS(113), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [515] = 3,
    ACTIONS(119), 1,
      anon_sym_LT,
    STATE(19), 1,
      sym_comment,
    ACTIONS(117), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [533] = 3,
    ACTIONS(123), 1,
      anon_sym_LT,
    STATE(20), 1,
      sym_comment,
    ACTIONS(121), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [551] = 3,
    ACTIONS(87), 1,
      anon_sym_LT,
    STATE(21), 1,
      sym_comment,
    ACTIONS(85), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [569] = 3,
    ACTIONS(127), 1,
      anon_sym_LT,
    STATE(22), 1,
      sym_comment,
    ACTIONS(125), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [587] = 3,
    ACTIONS(131), 1,
      anon_sym_LT,
    STATE(23), 1,
      sym_comment,
    ACTIONS(129), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [605] = 3,
    ACTIONS(83), 1,
      anon_sym_LT,
    STATE(24), 1,
      sym_comment,
    ACTIONS(81), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [623] = 3,
    ACTIONS(95), 1,
      anon_sym_LT,
    STATE(25), 1,
      sym_comment,
    ACTIONS(93), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [641] = 3,
    ACTIONS(99), 1,
      anon_sym_LT,
    STATE(26), 1,
      sym_comment,
    ACTIONS(97), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [659] = 3,
    ACTIONS(103), 1,
      anon_sym_LT,
    STATE(27), 1,
      sym_comment,
    ACTIONS(101), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [677] = 3,
    ACTIONS(107), 1,
      anon_sym_LT,
    STATE(28), 1,
      sym_comment,
    ACTIONS(105), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [695] = 3,
    ACTIONS(111), 1,
      anon_sym_LT,
    STATE(29), 1,
      sym_comment,
    ACTIONS(109), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [713] = 3,
    ACTIONS(115), 1,
      anon_sym_LT,
    STATE(30), 1,
      sym_comment,
    ACTIONS(113), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [731] = 3,
    ACTIONS(79), 1,
      anon_sym_LT,
    STATE(31), 1,
      sym_comment,
    ACTIONS(77), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [749] = 3,
    ACTIONS(123), 1,
      anon_sym_LT,
    STATE(32), 1,
      sym_comment,
    ACTIONS(121), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [767] = 3,
    ACTIONS(135), 1,
      anon_sym_LT,
    STATE(33), 1,
      sym_comment,
    ACTIONS(133), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [785] = 3,
    ACTIONS(135), 1,
      anon_sym_LT,
    STATE(34), 1,
      sym_comment,
    ACTIONS(133), 9,
      sym__implicit_end_tag,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [803] = 3,
    ACTIONS(127), 1,
      anon_sym_LT,
    STATE(35), 1,
      sym_comment,
    ACTIONS(125), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [821] = 3,
    ACTIONS(131), 1,
      anon_sym_LT,
    STATE(36), 1,
      sym_comment,
    ACTIONS(129), 9,
      sym_ignoreif_identifier,
      sym_unknown_identifier,
      sym__comment_start,
      sym_include_directive,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [839] = 7,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(137), 1,
      anon_sym_GT,
    ACTIONS(139), 1,
      anon_sym_SLASH_GT,
    ACTIONS(141), 1,
      sym_attribute_name,
    STATE(37), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_start_tag_repeat1,
    STATE(57), 1,
      sym_attribute,
  [861] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(145), 1,
      sym_attribute_name,
    STATE(57), 1,
      sym_attribute,
    ACTIONS(143), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(38), 2,
      sym_comment,
      aux_sym_start_tag_repeat1,
  [879] = 7,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(141), 1,
      sym_attribute_name,
    ACTIONS(148), 1,
      anon_sym_GT,
    ACTIONS(150), 1,
      anon_sym_SLASH_GT,
    STATE(39), 1,
      sym_comment,
    STATE(41), 1,
      aux_sym_start_tag_repeat1,
    STATE(57), 1,
      sym_attribute,
  [901] = 7,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(141), 1,
      sym_attribute_name,
    ACTIONS(148), 1,
      anon_sym_GT,
    ACTIONS(152), 1,
      anon_sym_SLASH_GT,
    STATE(37), 1,
      aux_sym_start_tag_repeat1,
    STATE(40), 1,
      sym_comment,
    STATE(57), 1,
      sym_attribute,
  [923] = 7,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(137), 1,
      anon_sym_GT,
    ACTIONS(141), 1,
      sym_attribute_name,
    ACTIONS(154), 1,
      anon_sym_SLASH_GT,
    STATE(38), 1,
      aux_sym_start_tag_repeat1,
    STATE(41), 1,
      sym_comment,
    STATE(57), 1,
      sym_attribute,
  [945] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(158), 1,
      anon_sym_EQ,
    STATE(42), 1,
      sym_comment,
    ACTIONS(156), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [960] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(143), 1,
      anon_sym_GT,
    ACTIONS(160), 1,
      sym_attribute_name,
    STATE(64), 1,
      sym_attribute,
    STATE(43), 2,
      sym_comment,
      aux_sym_start_tag_repeat1,
  [977] = 6,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(163), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      sym_attribute_name,
    STATE(43), 1,
      aux_sym_start_tag_repeat1,
    STATE(44), 1,
      sym_comment,
    STATE(64), 1,
      sym_attribute,
  [996] = 6,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(165), 1,
      sym_attribute_name,
    ACTIONS(167), 1,
      anon_sym_GT,
    STATE(43), 1,
      aux_sym_start_tag_repeat1,
    STATE(45), 1,
      sym_comment,
    STATE(64), 1,
      sym_attribute,
  [1015] = 6,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(165), 1,
      sym_attribute_name,
    ACTIONS(169), 1,
      anon_sym_GT,
    STATE(44), 1,
      aux_sym_start_tag_repeat1,
    STATE(46), 1,
      sym_comment,
    STATE(64), 1,
      sym_attribute,
  [1034] = 6,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(165), 1,
      sym_attribute_name,
    ACTIONS(171), 1,
      anon_sym_GT,
    STATE(45), 1,
      aux_sym_start_tag_repeat1,
    STATE(47), 1,
      sym_comment,
    STATE(64), 1,
      sym_attribute,
  [1053] = 6,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(173), 1,
      sym_attribute_value,
    ACTIONS(175), 1,
      anon_sym_SQUOTE,
    ACTIONS(177), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      sym_comment,
    STATE(76), 1,
      sym_quoted_attribute_value,
  [1072] = 6,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(179), 1,
      sym_attribute_value,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      sym_comment,
    STATE(60), 1,
      sym_quoted_attribute_value,
  [1091] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(185), 1,
      anon_sym_LT_SLASH,
    ACTIONS(187), 1,
      sym_raw_text,
    STATE(23), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_comment,
  [1107] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(51), 1,
      sym_comment,
    ACTIONS(189), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1119] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    ACTIONS(193), 1,
      sym_raw_text,
    STATE(10), 1,
      sym_end_tag,
    STATE(52), 1,
      sym_comment,
  [1135] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(185), 1,
      anon_sym_LT_SLASH,
    ACTIONS(195), 1,
      sym_raw_text,
    STATE(24), 1,
      sym_end_tag,
    STATE(53), 1,
      sym_comment,
  [1151] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    ACTIONS(197), 1,
      sym_raw_text,
    STATE(36), 1,
      sym_end_tag,
    STATE(54), 1,
      sym_comment,
  [1167] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(55), 1,
      sym_comment,
    ACTIONS(199), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1179] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(201), 1,
      anon_sym_EQ,
    STATE(56), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1193] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(57), 1,
      sym_comment,
    ACTIONS(203), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1205] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(205), 1,
      sym__start_tag_name,
    ACTIONS(207), 1,
      sym__script_start_tag_name,
    ACTIONS(209), 1,
      sym__style_start_tag_name,
    STATE(58), 1,
      sym_comment,
  [1221] = 5,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(207), 1,
      sym__script_start_tag_name,
    ACTIONS(209), 1,
      sym__style_start_tag_name,
    ACTIONS(211), 1,
      sym__start_tag_name,
    STATE(59), 1,
      sym_comment,
  [1237] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(60), 1,
      sym_comment,
    ACTIONS(213), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1249] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(185), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      sym_end_tag,
    STATE(61), 1,
      sym_comment,
  [1262] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
    ACTIONS(217), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(62), 1,
      sym_comment,
  [1275] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(63), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1286] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(64), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1297] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(65), 1,
      sym_comment,
    ACTIONS(219), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1308] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(221), 1,
      sym__end_tag_name,
    ACTIONS(223), 1,
      sym_erroneous_end_tag_name,
    STATE(66), 1,
      sym_comment,
  [1321] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(67), 1,
      sym_comment,
    ACTIONS(225), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1332] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(68), 1,
      sym_comment,
    ACTIONS(227), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1343] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(69), 1,
      sym_comment,
    ACTIONS(229), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1354] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    STATE(17), 1,
      sym_end_tag,
    STATE(70), 1,
      sym_comment,
  [1367] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(185), 1,
      anon_sym_LT_SLASH,
    STATE(29), 1,
      sym_end_tag,
    STATE(71), 1,
      sym_comment,
  [1380] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    STATE(16), 1,
      sym_end_tag,
    STATE(72), 1,
      sym_comment,
  [1393] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(215), 1,
      anon_sym_SQUOTE,
    ACTIONS(231), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(73), 1,
      sym_comment,
  [1406] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(233), 1,
      anon_sym_SQUOTE,
    ACTIONS(235), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(74), 1,
      sym_comment,
  [1419] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(233), 1,
      anon_sym_DQUOTE,
    ACTIONS(237), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(75), 1,
      sym_comment,
  [1432] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(76), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1443] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    STATE(77), 1,
      sym_comment,
    ACTIONS(189), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1454] = 4,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(223), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(239), 1,
      sym__end_tag_name,
    STATE(78), 1,
      sym_comment,
  [1467] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(223), 1,
      sym_erroneous_end_tag_name,
    STATE(79), 1,
      sym_comment,
  [1477] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(241), 1,
      anon_sym_GT,
    STATE(80), 1,
      sym_comment,
  [1487] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(243), 1,
      sym__doctype,
    STATE(81), 1,
      sym_comment,
  [1497] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(245), 1,
      aux_sym_comment_token1,
    STATE(82), 1,
      sym_comment,
  [1507] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(247), 1,
      anon_sym_GT,
    STATE(83), 1,
      sym_comment,
  [1517] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(249), 1,
      anon_sym_GT,
    STATE(84), 1,
      sym_comment,
  [1527] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(251), 1,
      aux_sym_comment_token1,
    STATE(85), 1,
      sym_comment,
  [1537] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(253), 1,
      anon_sym_GT,
    STATE(86), 1,
      sym_comment,
  [1547] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(255), 1,
      sym_include_directive,
    STATE(87), 1,
      sym_comment,
  [1557] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(257), 1,
      aux_sym_doctype_token1,
    STATE(88), 1,
      sym_comment,
  [1567] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(259), 1,
      aux_sym_comment_token1,
    STATE(89), 1,
      sym_comment,
  [1577] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(261), 1,
      anon_sym_GT,
    STATE(90), 1,
      sym_comment,
  [1587] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(263), 1,
      sym__comment_end,
    STATE(91), 1,
      sym_comment,
  [1597] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(265), 1,
      anon_sym_GT,
    STATE(92), 1,
      sym_comment,
  [1607] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(267), 1,
      sym__comment_content,
    STATE(93), 1,
      sym_comment,
  [1617] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(269), 1,
      anon_sym_SQUOTE,
    STATE(94), 1,
      sym_comment,
  [1627] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    STATE(95), 1,
      sym_comment,
  [1637] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(273), 1,
      sym__comment_end,
    STATE(96), 1,
      sym_comment,
  [1647] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(275), 1,
      anon_sym_SQUOTE,
    STATE(97), 1,
      sym_comment,
  [1657] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(275), 1,
      anon_sym_DQUOTE,
    STATE(98), 1,
      sym_comment,
  [1667] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(277), 1,
      sym__comment_end,
    STATE(99), 1,
      sym_comment,
  [1677] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(221), 1,
      sym__end_tag_name,
    STATE(100), 1,
      sym_comment,
  [1687] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(279), 1,
      aux_sym_doctype_token1,
    STATE(101), 1,
      sym_comment,
  [1697] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(281), 1,
      sym_erroneous_end_tag_name,
    STATE(102), 1,
      sym_comment,
  [1707] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(239), 1,
      sym__end_tag_name,
    STATE(103), 1,
      sym_comment,
  [1717] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    STATE(104), 1,
      sym_comment,
  [1727] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(285), 1,
      aux_sym_comment_token1,
    STATE(105), 1,
      sym_comment,
  [1737] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(287), 1,
      sym__doctype,
    STATE(106), 1,
      sym_comment,
  [1747] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(289), 1,
      sym__comment_content,
    STATE(107), 1,
      sym_comment,
  [1757] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(291), 1,
      sym__comment_content,
    STATE(108), 1,
      sym_comment,
  [1767] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(293), 1,
      aux_sym_comment_token1,
    STATE(109), 1,
      sym_comment,
  [1777] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(295), 1,
      aux_sym_comment_token1,
    STATE(110), 1,
      sym_comment,
  [1787] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(297), 1,
      sym_include_directive,
    STATE(111), 1,
      sym_comment,
  [1797] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(299), 1,
      sym_include_directive,
    STATE(112), 1,
      sym_comment,
  [1807] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(301), 1,
      aux_sym_comment_token1,
    STATE(113), 1,
      sym_comment,
  [1817] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(303), 1,
      aux_sym_comment_token1,
    STATE(114), 1,
      sym_comment,
  [1827] = 3,
    ACTIONS(3), 1,
      sym__comment_start,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
    STATE(115), 1,
      sym_comment,
  [1837] = 1,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 198,
  [SMALL_STATE(7)] = 243,
  [SMALL_STATE(8)] = 290,
  [SMALL_STATE(9)] = 335,
  [SMALL_STATE(10)] = 353,
  [SMALL_STATE(11)] = 371,
  [SMALL_STATE(12)] = 389,
  [SMALL_STATE(13)] = 407,
  [SMALL_STATE(14)] = 425,
  [SMALL_STATE(15)] = 443,
  [SMALL_STATE(16)] = 461,
  [SMALL_STATE(17)] = 479,
  [SMALL_STATE(18)] = 497,
  [SMALL_STATE(19)] = 515,
  [SMALL_STATE(20)] = 533,
  [SMALL_STATE(21)] = 551,
  [SMALL_STATE(22)] = 569,
  [SMALL_STATE(23)] = 587,
  [SMALL_STATE(24)] = 605,
  [SMALL_STATE(25)] = 623,
  [SMALL_STATE(26)] = 641,
  [SMALL_STATE(27)] = 659,
  [SMALL_STATE(28)] = 677,
  [SMALL_STATE(29)] = 695,
  [SMALL_STATE(30)] = 713,
  [SMALL_STATE(31)] = 731,
  [SMALL_STATE(32)] = 749,
  [SMALL_STATE(33)] = 767,
  [SMALL_STATE(34)] = 785,
  [SMALL_STATE(35)] = 803,
  [SMALL_STATE(36)] = 821,
  [SMALL_STATE(37)] = 839,
  [SMALL_STATE(38)] = 861,
  [SMALL_STATE(39)] = 879,
  [SMALL_STATE(40)] = 901,
  [SMALL_STATE(41)] = 923,
  [SMALL_STATE(42)] = 945,
  [SMALL_STATE(43)] = 960,
  [SMALL_STATE(44)] = 977,
  [SMALL_STATE(45)] = 996,
  [SMALL_STATE(46)] = 1015,
  [SMALL_STATE(47)] = 1034,
  [SMALL_STATE(48)] = 1053,
  [SMALL_STATE(49)] = 1072,
  [SMALL_STATE(50)] = 1091,
  [SMALL_STATE(51)] = 1107,
  [SMALL_STATE(52)] = 1119,
  [SMALL_STATE(53)] = 1135,
  [SMALL_STATE(54)] = 1151,
  [SMALL_STATE(55)] = 1167,
  [SMALL_STATE(56)] = 1179,
  [SMALL_STATE(57)] = 1193,
  [SMALL_STATE(58)] = 1205,
  [SMALL_STATE(59)] = 1221,
  [SMALL_STATE(60)] = 1237,
  [SMALL_STATE(61)] = 1249,
  [SMALL_STATE(62)] = 1262,
  [SMALL_STATE(63)] = 1275,
  [SMALL_STATE(64)] = 1286,
  [SMALL_STATE(65)] = 1297,
  [SMALL_STATE(66)] = 1308,
  [SMALL_STATE(67)] = 1321,
  [SMALL_STATE(68)] = 1332,
  [SMALL_STATE(69)] = 1343,
  [SMALL_STATE(70)] = 1354,
  [SMALL_STATE(71)] = 1367,
  [SMALL_STATE(72)] = 1380,
  [SMALL_STATE(73)] = 1393,
  [SMALL_STATE(74)] = 1406,
  [SMALL_STATE(75)] = 1419,
  [SMALL_STATE(76)] = 1432,
  [SMALL_STATE(77)] = 1443,
  [SMALL_STATE(78)] = 1454,
  [SMALL_STATE(79)] = 1467,
  [SMALL_STATE(80)] = 1477,
  [SMALL_STATE(81)] = 1487,
  [SMALL_STATE(82)] = 1497,
  [SMALL_STATE(83)] = 1507,
  [SMALL_STATE(84)] = 1517,
  [SMALL_STATE(85)] = 1527,
  [SMALL_STATE(86)] = 1537,
  [SMALL_STATE(87)] = 1547,
  [SMALL_STATE(88)] = 1557,
  [SMALL_STATE(89)] = 1567,
  [SMALL_STATE(90)] = 1577,
  [SMALL_STATE(91)] = 1587,
  [SMALL_STATE(92)] = 1597,
  [SMALL_STATE(93)] = 1607,
  [SMALL_STATE(94)] = 1617,
  [SMALL_STATE(95)] = 1627,
  [SMALL_STATE(96)] = 1637,
  [SMALL_STATE(97)] = 1647,
  [SMALL_STATE(98)] = 1657,
  [SMALL_STATE(99)] = 1667,
  [SMALL_STATE(100)] = 1677,
  [SMALL_STATE(101)] = 1687,
  [SMALL_STATE(102)] = 1697,
  [SMALL_STATE(103)] = 1707,
  [SMALL_STATE(104)] = 1717,
  [SMALL_STATE(105)] = 1727,
  [SMALL_STATE(106)] = 1737,
  [SMALL_STATE(107)] = 1747,
  [SMALL_STATE(108)] = 1757,
  [SMALL_STATE(109)] = 1767,
  [SMALL_STATE(110)] = 1777,
  [SMALL_STATE(111)] = 1787,
  [SMALL_STATE(112)] = 1797,
  [SMALL_STATE(113)] = 1807,
  [SMALL_STATE(114)] = 1817,
  [SMALL_STATE(115)] = 1827,
  [SMALL_STATE(116)] = 1837,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 7, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 7, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [271] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_include_comment = 8,
  ts_external_token_ignoreif_comment = 9,
  ts_external_token_normal_comment = 10,
  ts_external_token_include_identifier = 11,
  ts_external_token_ignoreif_identifier = 12,
  ts_external_token_unknown_identifier = 13,
  ts_external_token__comment_start = 14,
  ts_external_token_include_directive = 15,
  ts_external_token__comment_end = 16,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_include_comment] = sym_include_comment,
  [ts_external_token_ignoreif_comment] = sym_ignoreif_comment,
  [ts_external_token_normal_comment] = sym_normal_comment,
  [ts_external_token_include_identifier] = sym_include_identifier,
  [ts_external_token_ignoreif_identifier] = sym_ignoreif_identifier,
  [ts_external_token_unknown_identifier] = sym_unknown_identifier,
  [ts_external_token__comment_start] = sym__comment_start,
  [ts_external_token_include_directive] = sym_include_directive,
  [ts_external_token__comment_end] = sym__comment_end,
};

static const bool ts_external_scanner_states[13][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_include_comment] = true,
    [ts_external_token_ignoreif_comment] = true,
    [ts_external_token_normal_comment] = true,
    [ts_external_token_include_identifier] = true,
    [ts_external_token_ignoreif_identifier] = true,
    [ts_external_token_unknown_identifier] = true,
    [ts_external_token__comment_start] = true,
    [ts_external_token_include_directive] = true,
    [ts_external_token__comment_end] = true,
  },
  [2] = {
    [ts_external_token_ignoreif_identifier] = true,
    [ts_external_token_unknown_identifier] = true,
    [ts_external_token__comment_start] = true,
    [ts_external_token_include_directive] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_ignoreif_identifier] = true,
    [ts_external_token_unknown_identifier] = true,
    [ts_external_token__comment_start] = true,
    [ts_external_token_include_directive] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__comment_start] = true,
  },
  [5] = {
    [ts_external_token__comment_start] = true,
  },
  [6] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token__comment_start] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__comment_start] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token__comment_start] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token__comment_start] = true,
  },
  [10] = {
    [ts_external_token__comment_start] = true,
    [ts_external_token_include_directive] = true,
  },
  [11] = {
    [ts_external_token__comment_start] = true,
    [ts_external_token__comment_end] = true,
  },
  [12] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token__comment_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_olex2htm_external_scanner_create(void);
void tree_sitter_olex2htm_external_scanner_destroy(void *);
bool tree_sitter_olex2htm_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_olex2htm_external_scanner_serialize(void *, char *);
void tree_sitter_olex2htm_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_olex2htm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_olex2htm_external_scanner_create,
      tree_sitter_olex2htm_external_scanner_destroy,
      tree_sitter_olex2htm_external_scanner_scan,
      tree_sitter_olex2htm_external_scanner_serialize,
      tree_sitter_olex2htm_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "olex2htm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
