/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 12
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  aux_sym_include_comment_token1 = 5,
  aux_sym_include_comment_token2 = 6,
  sym_include_keyword = 7,
  sym_include_arg = 8,
  sym_include_sub_arg = 9,
  anon_sym_LT_BANG_DASH_DASH = 10,
  anon_sym_DASH_DASH_GT = 11,
  anon_sym_LT = 12,
  anon_sym_SLASH_GT = 13,
  anon_sym_LT_SLASH = 14,
  anon_sym_EQ = 15,
  sym_attribute_name = 16,
  sym_attribute_value = 17,
  sym_entity = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_quoted_attribute_value_token1 = 20,
  anon_sym_DQUOTE = 21,
  aux_sym_quoted_attribute_value_token2 = 22,
  sym_text = 23,
  sym__start_tag_name = 24,
  sym__script_start_tag_name = 25,
  sym__style_start_tag_name = 26,
  sym__end_tag_name = 27,
  sym_erroneous_end_tag_name = 28,
  sym__implicit_end_tag = 29,
  sym_raw_text = 30,
  sym_ignoreif_keyword = 31,
  sym_ignoreif_arg = 32,
  sym_ignoreif_comment_content = 33,
  sym_normal_comment_content = 34,
  sym_document = 35,
  sym_doctype = 36,
  sym__node = 37,
  sym_comment = 38,
  sym_include_comment = 39,
  sym_ignoreif_comment = 40,
  sym_normal_comment = 41,
  sym__beggin_comment_arg = 42,
  sym__end_comment_arg = 43,
  sym_element = 44,
  sym_script_element = 45,
  sym_style_element = 46,
  sym_start_tag = 47,
  sym_script_start_tag = 48,
  sym_style_start_tag = 49,
  sym_self_closing_tag = 50,
  sym_end_tag = 51,
  sym_erroneous_end_tag = 52,
  sym_attribute = 53,
  sym_quoted_attribute_value = 54,
  aux_sym_document_repeat1 = 55,
  aux_sym_start_tag_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [aux_sym_include_comment_token1] = "include_comment_token1",
  [aux_sym_include_comment_token2] = "include_comment_token2",
  [sym_include_keyword] = "include_keyword",
  [sym_include_arg] = "include_arg",
  [sym_include_sub_arg] = "include_sub_arg",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_ignoreif_keyword] = "ignoreif_keyword",
  [sym_ignoreif_arg] = "ignoreif_arg",
  [sym_ignoreif_comment_content] = "ignoreif_comment_content",
  [sym_normal_comment_content] = "normal_comment_content",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_comment] = "comment",
  [sym_include_comment] = "include_comment",
  [sym_ignoreif_comment] = "ignoreif_comment",
  [sym_normal_comment] = "normal_comment",
  [sym__beggin_comment_arg] = "_beggin_comment_arg",
  [sym__end_comment_arg] = "_end_comment_arg",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [aux_sym_include_comment_token1] = aux_sym_include_comment_token1,
  [aux_sym_include_comment_token2] = aux_sym_include_comment_token2,
  [sym_include_keyword] = sym_include_keyword,
  [sym_include_arg] = sym_include_arg,
  [sym_include_sub_arg] = sym_include_sub_arg,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_ignoreif_keyword] = sym_ignoreif_keyword,
  [sym_ignoreif_arg] = sym_ignoreif_arg,
  [sym_ignoreif_comment_content] = sym_ignoreif_comment_content,
  [sym_normal_comment_content] = sym_normal_comment_content,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_comment] = sym_comment,
  [sym_include_comment] = sym_include_comment,
  [sym_ignoreif_comment] = sym_ignoreif_comment,
  [sym_normal_comment] = sym_normal_comment,
  [sym__beggin_comment_arg] = sym__beggin_comment_arg,
  [sym__end_comment_arg] = sym__end_comment_arg,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_include_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_include_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_include_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_include_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_include_sub_arg] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_ignoreif_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_ignoreif_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_ignoreif_comment_content] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_comment_content] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_include_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_ignoreif_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__beggin_comment_arg] = {
    .visible = false,
    .named = true,
  },
  [sym__end_comment_arg] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 10,
  [29] = 9,
  [30] = 25,
  [31] = 11,
  [32] = 12,
  [33] = 13,
  [34] = 14,
  [35] = 16,
  [36] = 17,
  [37] = 18,
  [38] = 19,
  [39] = 20,
  [40] = 21,
  [41] = 22,
  [42] = 24,
  [43] = 43,
  [44] = 26,
  [45] = 27,
  [46] = 43,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 47,
  [51] = 51,
  [52] = 51,
  [53] = 49,
  [54] = 48,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 58,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 60,
  [66] = 64,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 62,
  [71] = 69,
  [72] = 72,
  [73] = 67,
  [74] = 74,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 68,
  [79] = 72,
  [80] = 63,
  [81] = 77,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 87,
  [89] = 85,
  [90] = 83,
  [91] = 91,
  [92] = 92,
  [93] = 86,
  [94] = 74,
  [95] = 95,
  [96] = 92,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 99,
  [111] = 104,
  [112] = 109,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 101,
  [117] = 113,
  [118] = 106,
  [119] = 105,
  [120] = 120,
  [121] = 103,
  [122] = 120,
  [123] = 107,
  [124] = 115,
  [125] = 100,
  [126] = 97,
  [127] = 114,
  [128] = 108,
  [129] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 95,
        '#', 14,
        '&', 3,
        '\'', 92,
        '-', 7,
        '/', 9,
        '<', 46,
        '=', 49,
        '>', 36,
        'D', 20,
        'd', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(95);
      if (lookahead == '\'') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0) ADVANCE(94);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '>') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 24:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(21);
      END_STATE();
    case 25:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(98);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 27:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(41);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(43);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '<') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(98);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_include_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_include_comment_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_include_keyword);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_include_arg);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_include_sub_arg);
      if (lookahead == '-') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_include_sub_arg);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(33);
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(98);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 31},
  [2] = {.lex_state = 31, .external_lex_state = 2},
  [3] = {.lex_state = 31, .external_lex_state = 2},
  [4] = {.lex_state = 31, .external_lex_state = 2},
  [5] = {.lex_state = 31, .external_lex_state = 2},
  [6] = {.lex_state = 31, .external_lex_state = 2},
  [7] = {.lex_state = 31},
  [8] = {.lex_state = 31},
  [9] = {.lex_state = 31, .external_lex_state = 2},
  [10] = {.lex_state = 31, .external_lex_state = 2},
  [11] = {.lex_state = 31},
  [12] = {.lex_state = 31},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 31},
  [15] = {.lex_state = 31, .external_lex_state = 2},
  [16] = {.lex_state = 31},
  [17] = {.lex_state = 31},
  [18] = {.lex_state = 31},
  [19] = {.lex_state = 31},
  [20] = {.lex_state = 31},
  [21] = {.lex_state = 31},
  [22] = {.lex_state = 31},
  [23] = {.lex_state = 31, .external_lex_state = 2},
  [24] = {.lex_state = 31},
  [25] = {.lex_state = 31},
  [26] = {.lex_state = 31},
  [27] = {.lex_state = 31},
  [28] = {.lex_state = 31},
  [29] = {.lex_state = 31},
  [30] = {.lex_state = 31, .external_lex_state = 2},
  [31] = {.lex_state = 31, .external_lex_state = 2},
  [32] = {.lex_state = 31, .external_lex_state = 2},
  [33] = {.lex_state = 31, .external_lex_state = 2},
  [34] = {.lex_state = 31, .external_lex_state = 2},
  [35] = {.lex_state = 31, .external_lex_state = 2},
  [36] = {.lex_state = 31, .external_lex_state = 2},
  [37] = {.lex_state = 31, .external_lex_state = 2},
  [38] = {.lex_state = 31, .external_lex_state = 2},
  [39] = {.lex_state = 31, .external_lex_state = 2},
  [40] = {.lex_state = 31, .external_lex_state = 2},
  [41] = {.lex_state = 31, .external_lex_state = 2},
  [42] = {.lex_state = 31, .external_lex_state = 2},
  [43] = {.lex_state = 31, .external_lex_state = 2},
  [44] = {.lex_state = 31, .external_lex_state = 2},
  [45] = {.lex_state = 31, .external_lex_state = 2},
  [46] = {.lex_state = 31},
  [47] = {.lex_state = 8, .external_lex_state = 3},
  [48] = {.lex_state = 8, .external_lex_state = 3},
  [49] = {.lex_state = 8, .external_lex_state = 3},
  [50] = {.lex_state = 8, .external_lex_state = 3},
  [51] = {.lex_state = 38, .external_lex_state = 4},
  [52] = {.lex_state = 38, .external_lex_state = 4},
  [53] = {.lex_state = 8, .external_lex_state = 3},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 8, .external_lex_state = 3},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0, .external_lex_state = 5},
  [63] = {.lex_state = 8, .external_lex_state = 3},
  [64] = {.lex_state = 0, .external_lex_state = 6},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 0, .external_lex_state = 6},
  [67] = {.lex_state = 0, .external_lex_state = 7},
  [68] = {.lex_state = 8, .external_lex_state = 3},
  [69] = {.lex_state = 0, .external_lex_state = 5},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 0, .external_lex_state = 5},
  [72] = {.lex_state = 8, .external_lex_state = 3},
  [73] = {.lex_state = 0, .external_lex_state = 7},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 8},
  [79] = {.lex_state = 8},
  [80] = {.lex_state = 8},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0, .external_lex_state = 5},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0, .external_lex_state = 5},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0, .external_lex_state = 5},
  [92] = {.lex_state = 0, .external_lex_state = 8},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 5},
  [96] = {.lex_state = 0, .external_lex_state = 8},
  [97] = {.lex_state = 26},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 27},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0, .external_lex_state = 9},
  [106] = {.lex_state = 38},
  [107] = {.lex_state = 0, .external_lex_state = 10},
  [108] = {.lex_state = 26},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 28},
  [115] = {.lex_state = 42},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 38},
  [119] = {.lex_state = 0, .external_lex_state = 9},
  [120] = {.lex_state = 0, .external_lex_state = 11},
  [121] = {.lex_state = 27},
  [122] = {.lex_state = 0, .external_lex_state = 11},
  [123] = {.lex_state = 0, .external_lex_state = 10},
  [124] = {.lex_state = 42},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 26},
  [127] = {.lex_state = 28},
  [128] = {.lex_state = 26},
  [129] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [sym_include_keyword] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_ignoreif_keyword] = ACTIONS(1),
    [sym_ignoreif_arg] = ACTIONS(1),
    [sym_ignoreif_comment_content] = ACTIONS(1),
    [sym_normal_comment_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(98),
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_comment] = STATE(7),
    [sym_include_comment] = STATE(29),
    [sym_ignoreif_comment] = STATE(29),
    [sym_normal_comment] = STATE(29),
    [sym__beggin_comment_arg] = STATE(52),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(71),
    [sym_style_start_tag] = STATE(62),
    [sym_self_closing_tag] = STATE(25),
    [sym_erroneous_end_tag] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_BANG] = ACTIONS(5),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(25), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_end_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(51), 1,
      sym__beggin_comment_arg,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    ACTIONS(23), 2,
      sym_entity,
      sym_text,
    STATE(9), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(3), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [53] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(19), 1,
      sym_end_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(51), 1,
      sym__beggin_comment_arg,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    ACTIONS(27), 2,
      sym_entity,
      sym_text,
    STATE(9), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [106] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(38), 1,
      sym_end_tag,
    STATE(51), 1,
      sym__beggin_comment_arg,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    ACTIONS(27), 2,
      sym_entity,
      sym_text,
    STATE(9), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [159] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(32), 1,
      sym_end_tag,
    STATE(51), 1,
      sym__beggin_comment_arg,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    ACTIONS(35), 2,
      sym_entity,
      sym_text,
    STATE(9), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(4), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [212] = 13,
    ACTIONS(39), 1,
      anon_sym_LT_BANG,
    ACTIONS(42), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(45), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      anon_sym_LT_SLASH,
    ACTIONS(54), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(51), 1,
      sym__beggin_comment_arg,
    STATE(69), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    ACTIONS(51), 2,
      sym_entity,
      sym_text,
    STATE(9), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [262] = 13,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym__beggin_comment_arg,
    STATE(62), 1,
      sym_style_start_tag,
    STATE(71), 1,
      sym_script_start_tag,
    ACTIONS(58), 2,
      sym_entity,
      sym_text,
    STATE(29), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [312] = 13,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_LT_BANG,
    ACTIONS(63), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(66), 1,
      anon_sym_LT,
    ACTIONS(69), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_self_closing_tag,
    STATE(52), 1,
      sym__beggin_comment_arg,
    STATE(62), 1,
      sym_style_start_tag,
    STATE(71), 1,
      sym_script_start_tag,
    ACTIONS(72), 2,
      sym_entity,
      sym_text,
    STATE(29), 3,
      sym_include_comment,
      sym_ignoreif_comment,
      sym_normal_comment,
    STATE(8), 8,
      sym_doctype,
      sym__node,
      sym_comment,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [362] = 2,
    ACTIONS(75), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(77), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [374] = 2,
    ACTIONS(79), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(81), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [386] = 2,
    ACTIONS(85), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [398] = 2,
    ACTIONS(89), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [410] = 2,
    ACTIONS(93), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [422] = 2,
    ACTIONS(97), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [434] = 2,
    ACTIONS(99), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(101), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [446] = 2,
    ACTIONS(105), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [458] = 2,
    ACTIONS(109), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [470] = 2,
    ACTIONS(113), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [482] = 2,
    ACTIONS(117), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [494] = 2,
    ACTIONS(121), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [506] = 2,
    ACTIONS(125), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [518] = 2,
    ACTIONS(129), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [530] = 2,
    ACTIONS(131), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(133), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [542] = 2,
    ACTIONS(137), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [554] = 2,
    ACTIONS(141), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [566] = 2,
    ACTIONS(145), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [578] = 2,
    ACTIONS(149), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [590] = 2,
    ACTIONS(79), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [602] = 2,
    ACTIONS(75), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [614] = 2,
    ACTIONS(141), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(139), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [626] = 2,
    ACTIONS(85), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(83), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [638] = 2,
    ACTIONS(89), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(87), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [650] = 2,
    ACTIONS(93), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(91), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [662] = 2,
    ACTIONS(97), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(95), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [674] = 2,
    ACTIONS(105), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(103), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [686] = 2,
    ACTIONS(109), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(107), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [698] = 2,
    ACTIONS(113), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(111), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [710] = 2,
    ACTIONS(117), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(115), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [722] = 2,
    ACTIONS(121), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(119), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [734] = 2,
    ACTIONS(125), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(123), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [746] = 2,
    ACTIONS(129), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(127), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [758] = 2,
    ACTIONS(137), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(135), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [770] = 2,
    ACTIONS(151), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(153), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [782] = 2,
    ACTIONS(145), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(143), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [794] = 2,
    ACTIONS(149), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(147), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [806] = 2,
    ACTIONS(151), 2,
      anon_sym_LT_BANG,
      anon_sym_LT,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [818] = 4,
    ACTIONS(155), 1,
      anon_sym_GT,
    ACTIONS(157), 1,
      anon_sym_SLASH_GT,
    ACTIONS(159), 1,
      sym_attribute_name,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [832] = 3,
    ACTIONS(163), 1,
      sym_attribute_name,
    ACTIONS(161), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [844] = 4,
    ACTIONS(159), 1,
      sym_attribute_name,
    ACTIONS(166), 1,
      anon_sym_GT,
    ACTIONS(168), 1,
      anon_sym_SLASH_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [858] = 4,
    ACTIONS(155), 1,
      anon_sym_GT,
    ACTIONS(159), 1,
      sym_attribute_name,
    ACTIONS(170), 1,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [872] = 5,
    ACTIONS(172), 1,
      aux_sym_include_comment_token1,
    ACTIONS(174), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(176), 1,
      sym_ignoreif_keyword,
    ACTIONS(178), 1,
      sym_normal_comment_content,
    STATE(31), 1,
      sym__end_comment_arg,
  [888] = 5,
    ACTIONS(180), 1,
      aux_sym_include_comment_token1,
    ACTIONS(182), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(184), 1,
      sym_ignoreif_keyword,
    ACTIONS(186), 1,
      sym_normal_comment_content,
    STATE(11), 1,
      sym__end_comment_arg,
  [904] = 4,
    ACTIONS(159), 1,
      sym_attribute_name,
    ACTIONS(166), 1,
      anon_sym_GT,
    ACTIONS(188), 1,
      anon_sym_SLASH_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [918] = 3,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(190), 1,
      sym_attribute_name,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [929] = 3,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_attribute_name,
    STATE(59), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [940] = 3,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(197), 1,
      anon_sym_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [951] = 3,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(199), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [962] = 4,
    ACTIONS(201), 1,
      sym_attribute_value,
    ACTIONS(203), 1,
      anon_sym_SQUOTE,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      sym_quoted_attribute_value,
  [975] = 3,
    ACTIONS(195), 1,
      sym_attribute_name,
    ACTIONS(207), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [986] = 2,
    ACTIONS(211), 1,
      anon_sym_EQ,
    ACTIONS(209), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [995] = 4,
    ACTIONS(213), 1,
      sym_attribute_value,
    ACTIONS(215), 1,
      anon_sym_SQUOTE,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    STATE(78), 1,
      sym_quoted_attribute_value,
  [1008] = 3,
    ACTIONS(219), 1,
      anon_sym_LT_SLASH,
    ACTIONS(221), 1,
      sym_raw_text,
    STATE(14), 1,
      sym_end_tag,
  [1018] = 1,
    ACTIONS(223), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1024] = 3,
    ACTIONS(225), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(227), 1,
      sym_ignoreif_comment_content,
    STATE(46), 1,
      sym__end_comment_arg,
  [1034] = 2,
    ACTIONS(229), 1,
      anon_sym_EQ,
    ACTIONS(209), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1042] = 3,
    ACTIONS(231), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(233), 1,
      sym_ignoreif_comment_content,
    STATE(43), 1,
      sym__end_comment_arg,
  [1052] = 3,
    ACTIONS(235), 1,
      sym__start_tag_name,
    ACTIONS(237), 1,
      sym__script_start_tag_name,
    ACTIONS(239), 1,
      sym__style_start_tag_name,
  [1062] = 1,
    ACTIONS(241), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1068] = 3,
    ACTIONS(243), 1,
      anon_sym_LT_SLASH,
    ACTIONS(245), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
  [1078] = 3,
    ACTIONS(243), 1,
      anon_sym_LT_SLASH,
    ACTIONS(247), 1,
      sym_raw_text,
    STATE(34), 1,
      sym_end_tag,
  [1088] = 3,
    ACTIONS(219), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 1,
      sym_raw_text,
    STATE(13), 1,
      sym_end_tag,
  [1098] = 1,
    ACTIONS(251), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1104] = 3,
    ACTIONS(237), 1,
      sym__script_start_tag_name,
    ACTIONS(239), 1,
      sym__style_start_tag_name,
    ACTIONS(253), 1,
      sym__start_tag_name,
  [1114] = 2,
    ACTIONS(255), 1,
      anon_sym_DQUOTE,
    ACTIONS(257), 1,
      aux_sym_quoted_attribute_value_token2,
  [1121] = 2,
    ACTIONS(259), 1,
      anon_sym_DASH_DASH_GT,
    STATE(45), 1,
      sym__end_comment_arg,
  [1128] = 2,
    ACTIONS(261), 1,
      anon_sym_DASH_DASH_GT,
    STATE(27), 1,
      sym__end_comment_arg,
  [1135] = 2,
    ACTIONS(263), 1,
      anon_sym_DASH_DASH_GT,
    STATE(28), 1,
      sym__end_comment_arg,
  [1142] = 1,
    ACTIONS(241), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1147] = 1,
    ACTIONS(251), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1152] = 1,
    ACTIONS(223), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1157] = 2,
    ACTIONS(265), 1,
      anon_sym_DASH_DASH_GT,
    STATE(10), 1,
      sym__end_comment_arg,
  [1164] = 1,
    ACTIONS(267), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1169] = 2,
    ACTIONS(219), 1,
      anon_sym_LT_SLASH,
    STATE(21), 1,
      sym_end_tag,
  [1176] = 1,
    ACTIONS(269), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1181] = 2,
    ACTIONS(219), 1,
      anon_sym_LT_SLASH,
    STATE(20), 1,
      sym_end_tag,
  [1188] = 2,
    ACTIONS(255), 1,
      anon_sym_SQUOTE,
    ACTIONS(271), 1,
      aux_sym_quoted_attribute_value_token1,
  [1195] = 2,
    ACTIONS(273), 1,
      anon_sym_DASH_DASH_GT,
    STATE(37), 1,
      sym__end_comment_arg,
  [1202] = 2,
    ACTIONS(275), 1,
      anon_sym_DASH_DASH_GT,
    STATE(18), 1,
      sym__end_comment_arg,
  [1209] = 2,
    ACTIONS(243), 1,
      anon_sym_LT_SLASH,
    STATE(39), 1,
      sym_end_tag,
  [1216] = 2,
    ACTIONS(243), 1,
      anon_sym_LT_SLASH,
    STATE(40), 1,
      sym_end_tag,
  [1223] = 1,
    ACTIONS(277), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1228] = 2,
    ACTIONS(279), 1,
      sym__end_tag_name,
    ACTIONS(281), 1,
      sym_erroneous_end_tag_name,
  [1235] = 2,
    ACTIONS(283), 1,
      anon_sym_SQUOTE,
    ACTIONS(285), 1,
      aux_sym_quoted_attribute_value_token1,
  [1242] = 2,
    ACTIONS(283), 1,
      anon_sym_DQUOTE,
    ACTIONS(287), 1,
      aux_sym_quoted_attribute_value_token2,
  [1249] = 1,
    ACTIONS(289), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1254] = 2,
    ACTIONS(281), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(291), 1,
      sym__end_tag_name,
  [1261] = 1,
    ACTIONS(293), 1,
      aux_sym_include_comment_token2,
  [1265] = 1,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [1269] = 1,
    ACTIONS(297), 1,
      anon_sym_GT,
  [1273] = 1,
    ACTIONS(299), 1,
      sym__doctype,
  [1277] = 1,
    ACTIONS(301), 1,
      anon_sym_SQUOTE,
  [1281] = 1,
    ACTIONS(303), 1,
      sym_include_keyword,
  [1285] = 1,
    ACTIONS(305), 1,
      aux_sym_doctype_token1,
  [1289] = 1,
    ACTIONS(307), 1,
      anon_sym_GT,
  [1293] = 1,
    ACTIONS(309), 1,
      sym_ignoreif_arg,
  [1297] = 1,
    ACTIONS(311), 1,
      aux_sym_include_comment_token1,
  [1301] = 1,
    ACTIONS(279), 1,
      sym__end_tag_name,
  [1305] = 1,
    ACTIONS(313), 1,
      aux_sym_include_comment_token2,
  [1309] = 1,
    ACTIONS(315), 1,
      anon_sym_GT,
  [1313] = 1,
    ACTIONS(317), 1,
      anon_sym_GT,
  [1317] = 1,
    ACTIONS(319), 1,
      anon_sym_GT,
  [1321] = 1,
    ACTIONS(321), 1,
      anon_sym_GT,
  [1325] = 1,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
  [1329] = 1,
    ACTIONS(323), 1,
      sym_include_arg,
  [1333] = 1,
    ACTIONS(325), 1,
      sym_include_sub_arg,
  [1337] = 1,
    ACTIONS(327), 1,
      anon_sym_SQUOTE,
  [1341] = 1,
    ACTIONS(327), 1,
      anon_sym_DQUOTE,
  [1345] = 1,
    ACTIONS(329), 1,
      aux_sym_include_comment_token1,
  [1349] = 1,
    ACTIONS(331), 1,
      sym_ignoreif_arg,
  [1353] = 1,
    ACTIONS(281), 1,
      sym_erroneous_end_tag_name,
  [1357] = 1,
    ACTIONS(333), 1,
      aux_sym_doctype_token1,
  [1361] = 1,
    ACTIONS(335), 1,
      sym_erroneous_end_tag_name,
  [1365] = 1,
    ACTIONS(291), 1,
      sym__end_tag_name,
  [1369] = 1,
    ACTIONS(337), 1,
      sym_include_sub_arg,
  [1373] = 1,
    ACTIONS(339), 1,
      sym__doctype,
  [1377] = 1,
    ACTIONS(341), 1,
      aux_sym_include_comment_token2,
  [1381] = 1,
    ACTIONS(343), 1,
      sym_include_arg,
  [1385] = 1,
    ACTIONS(345), 1,
      aux_sym_include_comment_token2,
  [1389] = 1,
    ACTIONS(347), 1,
      sym_include_keyword,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 106,
  [SMALL_STATE(5)] = 159,
  [SMALL_STATE(6)] = 212,
  [SMALL_STATE(7)] = 262,
  [SMALL_STATE(8)] = 312,
  [SMALL_STATE(9)] = 362,
  [SMALL_STATE(10)] = 374,
  [SMALL_STATE(11)] = 386,
  [SMALL_STATE(12)] = 398,
  [SMALL_STATE(13)] = 410,
  [SMALL_STATE(14)] = 422,
  [SMALL_STATE(15)] = 434,
  [SMALL_STATE(16)] = 446,
  [SMALL_STATE(17)] = 458,
  [SMALL_STATE(18)] = 470,
  [SMALL_STATE(19)] = 482,
  [SMALL_STATE(20)] = 494,
  [SMALL_STATE(21)] = 506,
  [SMALL_STATE(22)] = 518,
  [SMALL_STATE(23)] = 530,
  [SMALL_STATE(24)] = 542,
  [SMALL_STATE(25)] = 554,
  [SMALL_STATE(26)] = 566,
  [SMALL_STATE(27)] = 578,
  [SMALL_STATE(28)] = 590,
  [SMALL_STATE(29)] = 602,
  [SMALL_STATE(30)] = 614,
  [SMALL_STATE(31)] = 626,
  [SMALL_STATE(32)] = 638,
  [SMALL_STATE(33)] = 650,
  [SMALL_STATE(34)] = 662,
  [SMALL_STATE(35)] = 674,
  [SMALL_STATE(36)] = 686,
  [SMALL_STATE(37)] = 698,
  [SMALL_STATE(38)] = 710,
  [SMALL_STATE(39)] = 722,
  [SMALL_STATE(40)] = 734,
  [SMALL_STATE(41)] = 746,
  [SMALL_STATE(42)] = 758,
  [SMALL_STATE(43)] = 770,
  [SMALL_STATE(44)] = 782,
  [SMALL_STATE(45)] = 794,
  [SMALL_STATE(46)] = 806,
  [SMALL_STATE(47)] = 818,
  [SMALL_STATE(48)] = 832,
  [SMALL_STATE(49)] = 844,
  [SMALL_STATE(50)] = 858,
  [SMALL_STATE(51)] = 872,
  [SMALL_STATE(52)] = 888,
  [SMALL_STATE(53)] = 904,
  [SMALL_STATE(54)] = 918,
  [SMALL_STATE(55)] = 929,
  [SMALL_STATE(56)] = 940,
  [SMALL_STATE(57)] = 951,
  [SMALL_STATE(58)] = 962,
  [SMALL_STATE(59)] = 975,
  [SMALL_STATE(60)] = 986,
  [SMALL_STATE(61)] = 995,
  [SMALL_STATE(62)] = 1008,
  [SMALL_STATE(63)] = 1018,
  [SMALL_STATE(64)] = 1024,
  [SMALL_STATE(65)] = 1034,
  [SMALL_STATE(66)] = 1042,
  [SMALL_STATE(67)] = 1052,
  [SMALL_STATE(68)] = 1062,
  [SMALL_STATE(69)] = 1068,
  [SMALL_STATE(70)] = 1078,
  [SMALL_STATE(71)] = 1088,
  [SMALL_STATE(72)] = 1098,
  [SMALL_STATE(73)] = 1104,
  [SMALL_STATE(74)] = 1114,
  [SMALL_STATE(75)] = 1121,
  [SMALL_STATE(76)] = 1128,
  [SMALL_STATE(77)] = 1135,
  [SMALL_STATE(78)] = 1142,
  [SMALL_STATE(79)] = 1147,
  [SMALL_STATE(80)] = 1152,
  [SMALL_STATE(81)] = 1157,
  [SMALL_STATE(82)] = 1164,
  [SMALL_STATE(83)] = 1169,
  [SMALL_STATE(84)] = 1176,
  [SMALL_STATE(85)] = 1181,
  [SMALL_STATE(86)] = 1188,
  [SMALL_STATE(87)] = 1195,
  [SMALL_STATE(88)] = 1202,
  [SMALL_STATE(89)] = 1209,
  [SMALL_STATE(90)] = 1216,
  [SMALL_STATE(91)] = 1223,
  [SMALL_STATE(92)] = 1228,
  [SMALL_STATE(93)] = 1235,
  [SMALL_STATE(94)] = 1242,
  [SMALL_STATE(95)] = 1249,
  [SMALL_STATE(96)] = 1254,
  [SMALL_STATE(97)] = 1261,
  [SMALL_STATE(98)] = 1265,
  [SMALL_STATE(99)] = 1269,
  [SMALL_STATE(100)] = 1273,
  [SMALL_STATE(101)] = 1277,
  [SMALL_STATE(102)] = 1281,
  [SMALL_STATE(103)] = 1285,
  [SMALL_STATE(104)] = 1289,
  [SMALL_STATE(105)] = 1293,
  [SMALL_STATE(106)] = 1297,
  [SMALL_STATE(107)] = 1301,
  [SMALL_STATE(108)] = 1305,
  [SMALL_STATE(109)] = 1309,
  [SMALL_STATE(110)] = 1313,
  [SMALL_STATE(111)] = 1317,
  [SMALL_STATE(112)] = 1321,
  [SMALL_STATE(113)] = 1325,
  [SMALL_STATE(114)] = 1329,
  [SMALL_STATE(115)] = 1333,
  [SMALL_STATE(116)] = 1337,
  [SMALL_STATE(117)] = 1341,
  [SMALL_STATE(118)] = 1345,
  [SMALL_STATE(119)] = 1349,
  [SMALL_STATE(120)] = 1353,
  [SMALL_STATE(121)] = 1357,
  [SMALL_STATE(122)] = 1361,
  [SMALL_STATE(123)] = 1365,
  [SMALL_STATE(124)] = 1369,
  [SMALL_STATE(125)] = 1373,
  [SMALL_STATE(126)] = 1377,
  [SMALL_STATE(127)] = 1381,
  [SMALL_STATE(128)] = 1385,
  [SMALL_STATE(129)] = 1389,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_comment, 9, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_comment, 9, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_comment, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_comment, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_comment, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_comment, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignoreif_comment, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignoreif_comment, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignoreif_comment, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignoreif_comment, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [295] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_ignoreif_keyword = 8,
  ts_external_token_ignoreif_arg = 9,
  ts_external_token_ignoreif_comment_content = 10,
  ts_external_token_normal_comment_content = 11,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_ignoreif_keyword] = sym_ignoreif_keyword,
  [ts_external_token_ignoreif_arg] = sym_ignoreif_arg,
  [ts_external_token_ignoreif_comment_content] = sym_ignoreif_comment_content,
  [ts_external_token_normal_comment_content] = sym_normal_comment_content,
};

static const bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_ignoreif_keyword] = true,
    [ts_external_token_ignoreif_arg] = true,
    [ts_external_token_ignoreif_comment_content] = true,
    [ts_external_token_normal_comment_content] = true,
  },
  [2] = {
    [ts_external_token__implicit_end_tag] = true,
  },
  [3] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [4] = {
    [ts_external_token_ignoreif_keyword] = true,
    [ts_external_token_normal_comment_content] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
  },
  [6] = {
    [ts_external_token_ignoreif_comment_content] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
  },
  [9] = {
    [ts_external_token_ignoreif_arg] = true,
  },
  [10] = {
    [ts_external_token__end_tag_name] = true,
  },
  [11] = {
    [ts_external_token_erroneous_end_tag_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_olex2htm_external_scanner_create(void);
void tree_sitter_olex2htm_external_scanner_destroy(void *);
bool tree_sitter_olex2htm_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_olex2htm_external_scanner_serialize(void *, char *);
void tree_sitter_olex2htm_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_olex2htm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_olex2htm_external_scanner_create,
      tree_sitter_olex2htm_external_scanner_destroy,
      tree_sitter_olex2htm_external_scanner_scan,
      tree_sitter_olex2htm_external_scanner_serialize,
      tree_sitter_olex2htm_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "olex2htm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
